### ISSUE TITLE
MVP - Product Listings

### ISSUE THREAD

**Issue by pbalasubramanian** [pbalasubramanian/Goodsy_fsp#3]

**Comment by eshoule** [comment]
Good progress! Please see my comments below

- [x] Users can view a list of all products
- [x] Logged in users can create products with description, photo, price, quantity
- [ ] Logged in users can edit their product listings
- can't find any button to edit my listing that I create
- [ ] Logged in users can delete their own products
- can't find any button to delete my listing that I create
- [ ] You need more styling before I can close this MVP
- On your add listing form the Listing Details title is the wrong font.

![Screen Shot 2019-05-08 at 10 02 17 AM](https://user-images.githubusercontent.com/22806373/57393668-71286e00-7178-11e9-8e30-be3bc29e1ec5.png)

![Screen Shot 2019-05-08 at 10 03 52 AM](https://user-images.githubusercontent.com/22806373/57393759-a1700c80-7178-11e9-90de-5b33ec36db71.png)

**Comment by eshoule** [comment]
- [ ] When I delete a product, it does not disappear from the page until I refresh
